In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
country_df = pd.read_excel("IRENA_Statistics_Extract_2025H2.xlsx", sheet_name="Country")

In [13]:
region_df = pd.read_excel("IRENA_Statistics_Extract_2025H2.xlsx", sheet_name="Region ")

In [14]:
global_df = pd.read_excel("IRENA_Statistics_Extract_2025H2.xlsx", sheet_name="Global")

ANALYSIS AND CLEANING OF THE COUNTRY DATASET

In [15]:
country_df.head()

,Region,Sub-region,Country,ISO3 code,M49 code,RE or Non-RE,Group Technology,Technology,Sub-Technology,Producer Type,Year,Electricity Generation (GWh),Electricity Installed Capacity (MW),Heat Generation (TJ),Public Flows (2022 USD M),SDG 7a1 Intl. Public Flows (2022 USD M),SDG 7b1 RE capacity per capita (W/inhabitant)
0,Africa,Northern Africa,Algeria,DZA,12,Total Renewable,Bioenergy,Solid biofuels,Other primary solid biofuels n.e.s.,All types,2000,NaN,NaN,NaN,NaN,NaN,0.0
1,Africa,Northern Africa,Algeria,DZA,12,Total Renewable,Bioenergy,Solid biofuels,Other primary solid biofuels n.e.s.,All types,2001,NaN,NaN,NaN,NaN,NaN,0.0
2,Africa,Northern Africa,Algeria,DZA,12,Total Renewable,Bioenergy,Solid biofuels,Other primary solid biofuels n.e.s.,All types,2002,NaN,NaN,NaN,NaN,NaN,0.0
3,Africa,Northern Africa,Algeria,DZA,12,Total Renewable,Bioenergy,Solid biofuels,Other primary solid biofuels n.e.s.,All types,2003,NaN,NaN,NaN,NaN,NaN,0.0
4,Africa,Northern Africa,Algeria,DZA,12,Total Renewable,Bioenergy,Solid biofuels,Other primary solid biofuels n.e.s.,All types,2004,NaN,NaN,NaN,NaN,NaN,0.0

In [17]:
country_df.shape

(91743, 17)

In [16]:
country_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91743 entries, 0 to 91742
Data columns (total 17 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Region                                         91743 non-null  object
 1   Sub-region                                     91743 non-null  object
 2   Country                                        91743 non-null  object
 3   ISO3 code                                      91743 non-null  object
 4   M49 code                                       91743 non-null  int64
 5   RE or Non-RE                                   91743 non-null  object
 6   Group Technology                               91743 non-null  object
 7   Technology                                     91743 non-null  object
 8   Sub-Technology                                 91743 non-null  object
 9   Producer Type                                  91743 non-null  object
 10  Year                                           91743 non-null  int64
 11  Electricity Generation (GWh)                   37084 non-null  float64
 12  Electricity Installed Capacity (MW)            38387 non-null  float64
 13  Heat Generation (TJ)                           11168 non-null  float64
 14  Public Flows (2022 USD M)                      8429 non-null   float64
 15  SDG 7a1 Intl. Public Flows (2022 USD M)        5087 non-null   float64
 16  SDG 7b1 RE capacity per capita (W/inhabitant)  32112 non-null  float64
dtypes: float64(6), int64(2), object(9)
memory usage: 11.9+ MB

In [18]:
country_df.describe()

,M49 code,Year,Electricity Generation (GWh),Electricity Installed Capacity (MW),Heat Generation (TJ),Public Flows (2022 USD M),SDG 7a1 Intl. Public Flows (2022 USD M),SDG 7b1 RE capacity per capita (W/inhabitant)
count,91743.000000,91743.000000,3.708400e+04,3.838700e+04,1.116800e+04,8429.000000,5087.000000,32112.000000
mean,1229.715793,2012.624527,1.448429e+04,3.787969e+03,2.951583e+04,66.132037,43.249662,50.632276
std,8873.999102,6.969479,1.169155e+05,2.798736e+04,2.131821e+05,291.524054,157.508715,279.423188
min,4.000000,2000.000000,-5.874050e+02,1.000000e-03,3.100000e-02,0.000001,0.010000,0.000000
25%,208.000000,2007.000000,1.160750e+01,5.200000e+00,1.440000e+02,0.124572,0.120000,0.000000
50%,417.000000,2013.000000,2.042565e+02,6.900000e+01,1.380500e+03,2.111363,1.550000,0.000000
75%,643.000000,2019.000000,2.413088e+03,7.907000e+02,7.496750e+03,29.354210,21.230000,5.862704
max,99909.000000,2024.000000,5.579300e+06,1.247045e+06,5.244964e+06,9793.438766,4868.980000,6300.744570

In [19]:
country_df.isnull().sum()

Region                                               0
Sub-region                                           0
Country                                              0
ISO3 code                                            0
M49 code                                             0
RE or Non-RE                                         0
Group Technology                                     0
Technology                                           0
Sub-Technology                                       0
Producer Type                                        0
Year                                                 0
Electricity Generation (GWh)                     54659
Electricity Installed Capacity (MW)              53356
Heat Generation (TJ)                             80575
Public Flows (2022 USD M)                        83314
SDG 7a1 Intl. Public Flows (2022 USD M)          86656
SDG 7b1 RE capacity per capita (W/inhabitant)    59631
dtype: int64

In [20]:
# Numeric columns (int/float/bool/etc.)
country_num_df = country_df.select_dtypes(include=["float64"])

# Categorical columns (object, category, bool, etc.)
country_cat_df = country_df.select_dtypes(include=["object", "int64"])

In [21]:
for col in country_cat_df.columns:
    print(col)
    print("  unique count:", country_cat_df[col].nunique(dropna=False))
    print("  unique values:", country_cat_df[col].unique())
    print()

Region
  unique count: 7
  unique values: ['Africa' 'Americas' 'Asia' 'Europe' 'Multilateral' 'Oceania'
 'Unspecified countries']

Sub-region
  unique count: 21
  unique values: ['Northern Africa' 'Sub-Saharan Africa' 'Latin America and the Caribbean'
 'Northern America' '(blank)' 'Central Asia' 'Eastern Asia' 'Other Asia'
 'South-eastern Asia' 'Southern Asia' 'Western Asia' 'Eastern Europe'
 'Europe' 'Northern Europe' 'Southern Europe' 'Western Europe'
 'Multilateral' 'Australia and New Zealand' 'Melanesia' 'Micronesia'
 'Polynesia']

Country
  unique count: 235
  unique values: ['Algeria' 'Egypt' 'Libya' 'Morocco' 'Sudan (the)' 'Tunisia' 'Angola'
 'Benin' 'Botswana' 'Burkina Faso' 'Burundi' 'Cabo Verde' 'Cameroon'
 'Central African Republic (the)' 'Chad' 'Comoros (the)' 'Congo (the)'
 "Côte d'Ivoire" 'Democratic Republic of the Congo (the)' 'Djibouti'
 'Equatorial Guinea' 'Eritrea' 'Eswatini' 'Ethiopia' 'Gabon'
 'Gambia (the)' 'Ghana' 'Guinea' 'Guinea-Bissau' 'Kenya' 'Lesotho'
 'Liberia' 'Madagascar' 'Malawi' 'Mali' 'Mauritania' 'Mauritius' 'Mayotte'
 'Mozambique' 'Namibia' 'Niger (the)' 'Nigeria'
 'Residual/unallocated ODA: Sub-Saharan Africa' 'Réunion' 'Rwanda'
 'Saint Helena' 'Sao Tome and Principe' 'Senegal' 'Seychelles'
 'Sierra Leone' 'Somalia' 'South Africa' 'South Sudan' 'Togo' 'Uganda'
 'United Republic of Tanzania (the)' 'Zambia' 'Zimbabwe' 'Anguilla'
 'Antigua and Barbuda' 'Argentina' 'Aruba' 'Bahamas (the)' 'Barbados'
 'Belize' 'Bolivia (Plurinational State of)'
 'Bonaire, Sint Eustatius and Saba' 'Brazil' 'British Virgin Islands'
 'Cayman Islands' 'Chile' 'Colombia' 'Costa Rica' 'Cuba' 'Curaçao'
 'Dominica' 'Dominican Republic (the)' 'Ecuador' 'El Salvador'
 'Falkland Islands (Malvinas)' 'French Guiana' 'Grenada' 'Guadeloupe'
 'Guatemala' 'Guyana' 'Haiti' 'Honduras' 'Jamaica' 'Martinique' 'Mexico'
 'Montserrat' 'Nicaragua' 'Panama' 'Paraguay' 'Peru' 'Puerto Rico'
 'Residual/unallocated ODA: Latin America and the Caribbean'
 'Saint Barthélemy' 'Saint Kitts and Nevis' 'Saint Lucia'
 'Saint Martin (French Part)' 'Saint Vincent and the Grenadines'
 'Sint Maarten (Dutch Part)'
 'South Georgia and the South Sandwich Islands' 'Suriname'
 'Trinidad and Tobago' 'Turks and Caicos Islands'
 'United States Virgin Islands' 'Uruguay'
 'Venezuela (Bolivarian Republic of)' 'Canada' 'Greenland'
 'Saint Pierre and Miquelon' 'United States of America (the)'
 'Residual/unallocated ODA: Central Asia and Southern Asia'
 'Residual/unallocated ODA: Western Asia\xa0and Northern Africa'
 'Kazakhstan' 'Kyrgyzstan' 'Tajikistan' 'Turkmenistan' 'Uzbekistan'
 'China' 'China, Hong Kong Special Administrative Region' 'Chinese Taipei'
 "Democratic People's Republic of Korea (the)" 'Japan' 'Mongolia'
 'Republic of Korea (the)'
 'Residual/unallocated ODA: Eastern and South-eastern Asia'
 'Brunei Darussalam' 'Cambodia' 'Indonesia'
 "Lao People's Democratic Republic (the)" 'Malaysia' 'Myanmar'
 'Philippines (the)' 'Singapore' 'Thailand' 'Timor-Leste' 'Viet Nam'
 'Afghanistan' 'Bangladesh' 'Bhutan' 'India' 'Iran (Islamic Republic of)'
 'Maldives' 'Nepal' 'Pakistan' 'Sri Lanka' 'Armenia' 'Azerbaijan'
 'Bahrain' 'Cyprus' 'Georgia' 'Iraq' 'Israel' 'Jordan' 'Kuwait' 'Lebanon'
 'Oman' 'Qatar' 'Saudi Arabia' 'State of Palestine (the)'
 'Syrian Arab Republic (the)' 'Türkiye' 'United Arab Emirates (the)'
 'Yemen' 'European Union (27)' 'Belarus' 'Bulgaria' 'Czechia' 'Hungary'
 'Kosovo' 'Poland' 'Republic of Moldova (the)' 'Romania'
 'Russian Federation (the)' 'Slovakia' 'Ukraine'
 'Residual/unallocated ODA: Northern America and Europe' 'Denmark'
 'Estonia' 'Faroe Islands' 'Finland' 'Iceland' 'Ireland' 'Latvia'
 'Lithuania' 'Norway' 'Sweden'
 'United Kingdom of Great Britain and Northern Ireland (the)' 'Albania'
 'Andorra' 'Bosnia and Herzegovina' 'Croatia' 'Greece' 'Italy' 'Malta'
 'Montenegro' 'North Macedonia' 'Portugal' 'Serbia' 'Slovenia' 'Spain'
 'Austria' 'Belgium' 'France' 'Germany' 'Luxembourg'
 'Netherlands (Kingdom of the)' 'Switzerland' 'Multilateral'
 'Residual/unallocated ODA: Oceania excl. Aus. and N. Zealand' 'Australia'
 'New Zealand' 'Fiji' 'New Caledonia' 'Papua New Guinea' 'Solomon Islands'
 'Vanuatu' 'Guam' 'Kiribati' 'Marshall Islands (the)'
 'Micronesia (Federated States of)' 'Nauru' 'Palau' 'American Samoa'
 'Cook Islands (the)' 'French Polynesia' 'Niue' 'Samoa' 'Tokelau' 'Tonga'
 'Tuvalu' 'Unspecified countries']

ISO3 code
  unique count: 235
  unique values: ['DZA' 'EGY' 'LBY' 'MAR' 'SDN' 'TUN' 'AGO' 'BEN' 'BWA' 'BFA' 'BDI' 'CPV'
 'CMR' 'CAF' 'TCD' 'COM' 'COG' 'CIV' 'COD' 'DJI' 'GNQ' 'ERI' 'SWZ' 'ETH'
 'GAB' 'GMB' 'GHA' 'GIN' 'GNB' 'KEN' 'LSO' 'LBR' 'MDG' 'MWI' 'MLI' 'MRT'
 'MUS' 'MYT' 'MOZ' 'NAM' 'NER' 'NGA' 'XAF' 'REU' 'RWA' 'SHN' 'STP' 'SEN'
 'SYC' 'SLE' 'SOM' 'ZAF' 'SSD' 'TGO' 'UGA' 'TZA' 'ZMB' 'ZWE' 'AIA' 'ATG'
 'ARG' 'ABW' 'BHS' 'BRB' 'BLZ' 'BOL' 'BES' 'BRA' 'VGB' 'CYM' 'CHL' 'COL'
 'CRI' 'CUB' 'CUW' 'DMA' 'DOM' 'ECU' 'SLV' 'FLK' 'GUF' 'GRD' 'GLP' 'GTM'
 'GUY' 'HTI' 'HND' 'JAM' 'MTQ' 'MEX' 'MSR' 'NIC' 'PAN' 'PRY' 'PER' 'PRI'
 'XLA' 'BLM' 'KNA' 'LCA' 'MAF' 'VCT' 'SXM' 'SGS' 'SUR' 'TTO' 'TCA' 'VIR'
 'URY' 'VEN' 'CAN' 'GRL' 'SPM' 'USA' 'XCS' 'XME' 'KAZ' 'KGZ' 'TJK' 'TKM'
 'UZB' 'CHN' 'HKG' 'TWN' 'PRK' 'JPN' 'MNG' 'KOR' 'XAS' 'BRN' 'KHM' 'IDN'
 'LAO' 'MYS' 'MMR' 'PHL' 'SGP' 'THA' 'TLS' 'VNM' 'AFG' 'BGD' 'BTN' 'IND'
 'IRN' 'MDV' 'NPL' 'PAK' 'LKA' 'ARM' 'AZE' 'BHR' 'CYP' 'GEO' 'IRQ' 'ISR'
 'JOR' 'KWT' 'LBN' 'OMN' 'QAT' 'SAU' 'PSE' 'SYR' 'TUR' 'ARE' 'YEM' 'EUE'
 'BLR' 'BGR' 'CZE' 'HUN' 'XKX' 'POL' 'MDA' 'ROU' 'RUS' 'SVK' 'UKR' 'XAA'
 'DNK' 'EST' 'FRO' 'FIN' 'ISL' 'IRL' 'LVA' 'LTU' 'NOR' 'SWE' 'GBR' 'ALB'
 'AND' 'BIH' 'HRV' 'GRC' 'ITA' 'MLT' 'MNE' 'MKD' 'PRT' 'SRB' 'SVN' 'ESP'
 'AUT' 'BEL' 'FRA' 'DEU' 'LUX' 'NLD' 'CHE' 'XMX' 'XOC' 'AUS' 'NZL' 'FJI'
 'NCL' 'PNG' 'SLB' 'VUT' 'GUM' 'KIR' 'MHL' 'FSM' 'NRU' 'PLW' 'ASM' 'COK'
 'PYF' 'NIU' 'WSM' 'TKL' 'TON' 'TUV' 'XDX']

M49 code
  unique count: 235
  unique values: [   12   818   434   504   729   788    24   204    72   854   108   132
   120   140   148   174   178   384   180   262   226   232   748   231
   266   270   288   324   624   404   426   430   450   454   466   478
   480   175   508   516   562   566 99039   638   646   654   678   686
   690   694   706   710   728   768   800   834   894   716   660    28
    32   533    44    52    84    68   535    76    92   136   152   170
   188   192   531   212   214   218   222   238   254   308   312   320
   328   332   340   388   474   484   500   558   591   600   604   630
 99037   652   659   662   663   670   534   239   740   780   796   850
   858   862   124   304   666   840 99035 99040   398   417   762   795
   860   156   344   158   408   392   496   410 99036    96   116   360
   418   458   104   608   702   764   626   704     4    50    64   356
   364   462   524   586   144    51    31    48   196   268   368   376
   400   414   422   512   634   682   275   760   792   784   887 99906
   112   100   203   348   412   616   498   642   643   703   804 99050
   208   233   234   246   352   372   428   440   578   752   826     8
    20    70   191   300   380   470   499   807   620   688   705   724
    40    56   250   276   442   528   756 99909 99038    36   554   242
   540   598    90   548   316   296   584   583   520   585    16   184
   258   570   882   772   776   798 99049]

RE or Non-RE
  unique count: 2
  unique values: ['Total Renewable' 'Total Non-Renewable']

Group Technology
  unique count: 12
  unique values: ['Bioenergy' 'Geothermal energy' 'Hydropower (excl. Pumped Storage)'
 'Marine energy' 'Multiple renewables*' 'Solar energy' 'Wind energy'
 'Other renewable energy' 'Fossil fuels' 'Nuclear'
 'Other non-renewable energy' 'Pumped storage']

Technology
  unique count: 23
  unique values: ['Solid biofuels' 'Geothermal energy' 'Renewable hydropower'
 'Marine energy' 'Multiple renewables*' 'Solar energy'
 'Solar photovoltaic' 'Solar thermal energy' 'Onshore wind energy'
 'Biogas' 'Liquid biofuels' 'Renewable municipal waste'
 'Mixed Hydro Plants' 'Offshore wind energy' 'Other renewable energy'
 'Natural gas' 'Oil' 'Nuclear' 'Coal and peat' 'Fossil fuels n.e.s.'
 'Non-renewable municipal waste' 'Pumped storage'
 'Other non-renewable energy']

Sub-Technology
  unique count: 47
  unique values: ['Other primary solid biofuels n.e.s.' 'Geothermal energy'
 'Renewable hydropower' 'Marine energy' 'Multiple renewables*'
 'Solar energy' 'Off-grid Solar photovoltaic' 'On-grid Solar photovoltaic'
 'Concentrated solar power' 'Onshore wind energy' 'Sewage sludge gas'
 'Bagasse' 'Landfill gas' 'Solar thermal energy' 'Biogas'
 'Other biogases from anaerobic fermentation' 'Other liquid biofuels'
 'Wood waste' 'Other vegetal and agricultural waste'
 'Renewable municipal waste' 'Rice husks' 'Conventional biodiesel'
 'Animal waste' 'Straw' 'Wood fuel' 'Liquid biofuels'
 'Conventional biogasoline' 'Biomass pellets and briquettes'
 'Biogases from thermal processes' 'Biodiesel' 'Biogasoline'
 'Black liquor' 'Energy crops' 'Biogas n.e.s.' 'Mixed Hydro Plants'
 'Offshore wind energy' 'Renewable industrial waste'
 'Other renewable energy' 'Other solar thermal energy' 'Natural gas' 'Oil'
 'Nuclear' 'Coal and peat' 'Fossil fuels n.e.s.'
 'Non-renewable municipal waste' 'Pumped storage'
 'Other non-renewable energy']

Producer Type
  unique count: 5
  unique values: ['All types' 'On-grid electricity' 'Off-grid electricity'
 'Combined Heat and Power (CHP)' 'Heat (Commercial)']

Year
  unique count: 25
  unique values: [2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013
 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024]

In [22]:
cat_uniques = {col: country_cat_df[col].unique() for col in country_cat_df.columns}
cat_unique_counts = country_cat_df.nunique(dropna=False)

In [26]:
country_cat_df.isnull().sum()

Region              0
Sub-region          0
Country             0
ISO3 code           0
M49 code            0
RE or Non-RE        0
Group Technology    0
Technology          0
Sub-Technology      0
Producer Type       0
Year                0
dtype: int64

In [27]:
country_num_df.isnull().sum()

Electricity Generation (GWh)                     54659
Electricity Installed Capacity (MW)              53356
Heat Generation (TJ)                             80575
Public Flows (2022 USD M)                        83314
SDG 7a1 Intl. Public Flows (2022 USD M)          86656
SDG 7b1 RE capacity per capita (W/inhabitant)    59631
dtype: int64

In [32]:
country_df['Group Technology'].unique()
#country_df['Group Technology'].nunique()

array(['Bioenergy', 'Geothermal energy',
       'Hydropower (excl. Pumped Storage)', 'Marine energy',
       'Multiple renewables*', 'Solar energy', 'Wind energy',
       'Other renewable energy', 'Fossil fuels', 'Nuclear',
       'Other non-renewable energy', 'Pumped storage'], dtype=object)

In [34]:
Tech_Country_Region = country_df.groupby(['Country', 'Region'])['Group Technology'].unique()

In [35]:
print(Tech_Country_Region)

Country                             Region
Afghanistan                         Asia        [Bioenergy, Geothermal energy, Hydropower (exc...
Albania                             Europe      [Bioenergy, Geothermal energy, Hydropower (exc...
Algeria                             Africa      [Bioenergy, Geothermal energy, Hydropower (exc...
American Samoa                      Oceania     [Bioenergy, Geothermal energy, Hydropower (exc...
Andorra                             Europe      [Bioenergy, Geothermal energy, Hydropower (exc...
                                                                      ...
Venezuela (Bolivarian Republic of)  Americas    [Bioenergy, Geothermal energy, Hydropower (exc...
Viet Nam                            Asia        [Bioenergy, Geothermal energy, Hydropower (exc...
Yemen                               Asia        [Bioenergy, Geothermal energy, Hydropower (exc...
Zambia                              Africa      [Bioenergy, Geothermal energy, Hydropower (exc...
Zimbabwe                            Africa      [Bioenergy, Geothermal energy, Hydropower (exc...
Name: Group Technology, Length: 235, dtype: object

In [36]:
Tech_Country = country_df.groupby('Country')['Group Technology'].unique()

In [40]:
print(Tech_Country)

Country
Afghanistan                           [Bioenergy, Geothermal energy, Hydropower (exc...
Albania                               [Bioenergy, Geothermal energy, Hydropower (exc...
Algeria                               [Bioenergy, Geothermal energy, Hydropower (exc...
American Samoa                        [Bioenergy, Geothermal energy, Hydropower (exc...
Andorra                               [Bioenergy, Geothermal energy, Hydropower (exc...
                                                            ...
Venezuela (Bolivarian Republic of)    [Bioenergy, Geothermal energy, Hydropower (exc...
Viet Nam                              [Bioenergy, Geothermal energy, Hydropower (exc...
Yemen                                 [Bioenergy, Geothermal energy, Hydropower (exc...
Zambia                                [Bioenergy, Geothermal energy, Hydropower (exc...
Zimbabwe                              [Bioenergy, Geothermal energy, Hydropower (exc...
Name: Group Technology, Length: 235, dtype: object

In [42]:
TCC = country_df.groupby("Country")["Group Technology"].sum().reset_index()

In [43]:
print(TCC)

                                Country  \
0                           Afghanistan
1                               Albania
2                               Algeria
3                        American Samoa
4                               Andorra
..                                  ...
230  Venezuela (Bolivarian Republic of)
231                            Viet Nam
232                               Yemen
233                              Zambia
234                            Zimbabwe

                                      Group Technology
0    BioenergyBioenergyBioenergyBioenergyBioenergyB...
1    BioenergyBioenergyBioenergyBioenergyBioenergyB...
2    BioenergyBioenergyBioenergyBioenergyBioenergyB...
3    BioenergyBioenergyBioenergyBioenergyBioenergyB...
4    BioenergyBioenergyBioenergyBioenergyBioenergyB...
..                                                 ...
230  BioenergyBioenergyBioenergyBioenergyBioenergyB...
231  BioenergyBioenergyBioenergyBioenergyBioenergyB...
232  BioenergyBioenergyBioenergyBioenergyBioenergyB...
233  BioenergyBioenergyBioenergyBioenergyBioenergyB...
234  BioenergyBioenergyBioenergyBioenergyBioenergyB...

[235 rows x 2 columns]

In [37]:
Tech_Region = country_df.groupby('Region')['Group Technology'].unique()

In [44]:
print(Tech_Region)

Region
Africa                   [Bioenergy, Geothermal energy, Hydropower (exc...
Americas                 [Bioenergy, Geothermal energy, Hydropower (exc...
Asia                     [Bioenergy, Hydropower (excl. Pumped Storage),...
Europe                   [Multiple renewables*, Bioenergy, Geothermal e...
Multilateral             [Hydropower (excl. Pumped Storage), Multiple r...
Oceania                  [Bioenergy, Geothermal energy, Hydropower (exc...
Unspecified countries    [Bioenergy, Geothermal energy, Hydropower (exc...
Name: Group Technology, dtype: object

In [45]:
TCR = country_df.groupby("Region")["Group Technology"].sum().reset_index()

In [46]:
print(TCR)

                  Region                                   Group Technology
0                 Africa  BioenergyBioenergyBioenergyBioenergyBioenergyB...
1               Americas  BioenergyBioenergyBioenergyBioenergyBioenergyB...
2                   Asia  BioenergyBioenergyHydropower (excl. Pumped Sto...
3                 Europe  Multiple renewables*Multiple renewables*Multip...
4           Multilateral  Hydropower (excl. Pumped Storage)Multiple rene...
5                Oceania  BioenergyBioenergyGeothermal energyHydropower ...
6  Unspecified countries  BioenergyBioenergyBioenergyBioenergyBioenergyB...