In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
country_df = pd.read_excel("IRENA_Statistics_Extract_2025H2.xlsx", sheet_name="Country")

In [3]:
region_df = pd.read_excel("IRENA_Statistics_Extract_2025H2.xlsx", sheet_name="Region ")

In [4]:
global_df = pd.read_excel("IRENA_Statistics_Extract_2025H2.xlsx", sheet_name="Global")

ANALYSIS AND CLEANING OF THE COUNTRY DATASET

In [5]:
country_df.head()

,Region,Sub-region,Country,ISO3 code,M49 code,RE or Non-RE,Group Technology,Technology,Sub-Technology,Producer Type,Year,Electricity Generation (GWh),Electricity Installed Capacity (MW),Heat Generation (TJ),Public Flows (2022 USD M),SDG 7a1 Intl. Public Flows (2022 USD M),SDG 7b1 RE capacity per capita (W/inhabitant)
0,Africa,Northern Africa,Algeria,DZA,12,Total Renewable,Bioenergy,Solid biofuels,Other primary solid biofuels n.e.s.,All types,2000,NaN,NaN,NaN,NaN,NaN,0.0
1,Africa,Northern Africa,Algeria,DZA,12,Total Renewable,Bioenergy,Solid biofuels,Other primary solid biofuels n.e.s.,All types,2001,NaN,NaN,NaN,NaN,NaN,0.0
2,Africa,Northern Africa,Algeria,DZA,12,Total Renewable,Bioenergy,Solid biofuels,Other primary solid biofuels n.e.s.,All types,2002,NaN,NaN,NaN,NaN,NaN,0.0
3,Africa,Northern Africa,Algeria,DZA,12,Total Renewable,Bioenergy,Solid biofuels,Other primary solid biofuels n.e.s.,All types,2003,NaN,NaN,NaN,NaN,NaN,0.0
4,Africa,Northern Africa,Algeria,DZA,12,Total Renewable,Bioenergy,Solid biofuels,Other primary solid biofuels n.e.s.,All types,2004,NaN,NaN,NaN,NaN,NaN,0.0

In [6]:
country_df.shape

(91743, 17)

In [7]:
country_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91743 entries, 0 to 91742
Data columns (total 17 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Region                                         91743 non-null  object
 1   Sub-region                                     91743 non-null  object
 2   Country                                        91743 non-null  object
 3   ISO3 code                                      91743 non-null  object
 4   M49 code                                       91743 non-null  int64
 5   RE or Non-RE                                   91743 non-null  object
 6   Group Technology                               91743 non-null  object
 7   Technology                                     91743 non-null  object
 8   Sub-Technology                                 91743 non-null  object
 9   Producer Type                                  91743 non-null  object
 10  Year                                           91743 non-null  int64
 11  Electricity Generation (GWh)                   37084 non-null  float64
 12  Electricity Installed Capacity (MW)            38387 non-null  float64
 13  Heat Generation (TJ)                           11168 non-null  float64
 14  Public Flows (2022 USD M)                      8429 non-null   float64
 15  SDG 7a1 Intl. Public Flows (2022 USD M)        5087 non-null   float64
 16  SDG 7b1 RE capacity per capita (W/inhabitant)  32112 non-null  float64
dtypes: float64(6), int64(2), object(9)
memory usage: 11.9+ MB

In [8]:
country_df.describe()

,M49 code,Year,Electricity Generation (GWh),Electricity Installed Capacity (MW),Heat Generation (TJ),Public Flows (2022 USD M),SDG 7a1 Intl. Public Flows (2022 USD M),SDG 7b1 RE capacity per capita (W/inhabitant)
count,91743.000000,91743.000000,3.708400e+04,3.838700e+04,1.116800e+04,8429.000000,5087.000000,32112.000000
mean,1229.715793,2012.624527,1.448429e+04,3.787969e+03,2.951583e+04,66.132037,43.249662,50.632276
std,8873.999102,6.969479,1.169155e+05,2.798736e+04,2.131821e+05,291.524054,157.508715,279.423188
min,4.000000,2000.000000,-5.874050e+02,1.000000e-03,3.100000e-02,0.000001,0.010000,0.000000
25%,208.000000,2007.000000,1.160750e+01,5.200000e+00,1.440000e+02,0.124572,0.120000,0.000000
50%,417.000000,2013.000000,2.042565e+02,6.900000e+01,1.380500e+03,2.111363,1.550000,0.000000
75%,643.000000,2019.000000,2.413088e+03,7.907000e+02,7.496750e+03,29.354210,21.230000,5.862704
max,99909.000000,2024.000000,5.579300e+06,1.247045e+06,5.244964e+06,9793.438766,4868.980000,6300.744570

In [9]:
country_df.isnull().sum()

Region                                               0
Sub-region                                           0
Country                                              0
ISO3 code                                            0
M49 code                                             0
RE or Non-RE                                         0
Group Technology                                     0
Technology                                           0
Sub-Technology                                       0
Producer Type                                        0
Year                                                 0
Electricity Generation (GWh)                     54659
Electricity Installed Capacity (MW)              53356
Heat Generation (TJ)                             80575
Public Flows (2022 USD M)                        83314
SDG 7a1 Intl. Public Flows (2022 USD M)          86656
SDG 7b1 RE capacity per capita (W/inhabitant)    59631
dtype: int64

In [10]:
# Numeric columns (int/float/bool/etc.)
country_num_df = country_df.select_dtypes(include=["float64"])

# Categorical columns (object, category, bool, etc.)
country_cat_df = country_df.select_dtypes(include=["object", "int64"])

In [11]:
for col in country_cat_df.columns:
    print(col)
    print("  unique count:", country_cat_df[col].nunique(dropna=False))
    print("  unique values:", country_cat_df[col].unique())
    print()

Region
  unique count: 7
  unique values: ['Africa' 'Americas' 'Asia' 'Europe' 'Multilateral' 'Oceania'
 'Unspecified countries']

Sub-region
  unique count: 21
  unique values: ['Northern Africa' 'Sub-Saharan Africa' 'Latin America and the Caribbean'
 'Northern America' '(blank)' 'Central Asia' 'Eastern Asia' 'Other Asia'
 'South-eastern Asia' 'Southern Asia' 'Western Asia' 'Eastern Europe'
 'Europe' 'Northern Europe' 'Southern Europe' 'Western Europe'
 'Multilateral' 'Australia and New Zealand' 'Melanesia' 'Micronesia'
 'Polynesia']

Country
  unique count: 235
  unique values: ['Algeria' 'Egypt' 'Libya' 'Morocco' 'Sudan (the)' 'Tunisia' 'Angola'
 'Benin' 'Botswana' 'Burkina Faso' 'Burundi' 'Cabo Verde' 'Cameroon'
 'Central African Republic (the)' 'Chad' 'Comoros (the)' 'Congo (the)'
 "Côte d'Ivoire" 'Democratic Republic of the Congo (the)' 'Djibouti'
 'Equatorial Guinea' 'Eritrea' 'Eswatini' 'Ethiopia' 'Gabon'
 'Gambia (the)' 'Ghana' 'Guinea' 'Guinea-Bissau' 'Kenya' 'Lesotho'
 'Liberia' 'Madagascar' 'Malawi' 'Mali' 'Mauritania' 'Mauritius' 'Mayotte'
 'Mozambique' 'Namibia' 'Niger (the)' 'Nigeria'
 'Residual/unallocated ODA: Sub-Saharan Africa' 'Réunion' 'Rwanda'
 'Saint Helena' 'Sao Tome and Principe' 'Senegal' 'Seychelles'
 'Sierra Leone' 'Somalia' 'South Africa' 'South Sudan' 'Togo' 'Uganda'
 'United Republic of Tanzania (the)' 'Zambia' 'Zimbabwe' 'Anguilla'
 'Antigua and Barbuda' 'Argentina' 'Aruba' 'Bahamas (the)' 'Barbados'
 'Belize' 'Bolivia (Plurinational State of)'
 'Bonaire, Sint Eustatius and Saba' 'Brazil' 'British Virgin Islands'
 'Cayman Islands' 'Chile' 'Colombia' 'Costa Rica' 'Cuba' 'Curaçao'
 'Dominica' 'Dominican Republic (the)' 'Ecuador' 'El Salvador'
 'Falkland Islands (Malvinas)' 'French Guiana' 'Grenada' 'Guadeloupe'
 'Guatemala' 'Guyana' 'Haiti' 'Honduras' 'Jamaica' 'Martinique' 'Mexico'
 'Montserrat' 'Nicaragua' 'Panama' 'Paraguay' 'Peru' 'Puerto Rico'
 'Residual/unallocated ODA: Latin America and the Caribbean'
 'Saint Barthélemy' 'Saint Kitts and Nevis' 'Saint Lucia'
 'Saint Martin (French Part)' 'Saint Vincent and the Grenadines'
 'Sint Maarten (Dutch Part)'
 'South Georgia and the South Sandwich Islands' 'Suriname'
 'Trinidad and Tobago' 'Turks and Caicos Islands'
 'United States Virgin Islands' 'Uruguay'
 'Venezuela (Bolivarian Republic of)' 'Canada' 'Greenland'
 'Saint Pierre and Miquelon' 'United States of America (the)'
 'Residual/unallocated ODA: Central Asia and Southern Asia'
 'Residual/unallocated ODA: Western Asia\xa0and Northern Africa'
 'Kazakhstan' 'Kyrgyzstan' 'Tajikistan' 'Turkmenistan' 'Uzbekistan'
 'China' 'China, Hong Kong Special Administrative Region' 'Chinese Taipei'
 "Democratic People's Republic of Korea (the)" 'Japan' 'Mongolia'
 'Republic of Korea (the)'
 'Residual/unallocated ODA: Eastern and South-eastern Asia'
 'Brunei Darussalam' 'Cambodia' 'Indonesia'
 "Lao People's Democratic Republic (the)" 'Malaysia' 'Myanmar'
 'Philippines (the)' 'Singapore' 'Thailand' 'Timor-Leste' 'Viet Nam'
 'Afghanistan' 'Bangladesh' 'Bhutan' 'India' 'Iran (Islamic Republic of)'
 'Maldives' 'Nepal' 'Pakistan' 'Sri Lanka' 'Armenia' 'Azerbaijan'
 'Bahrain' 'Cyprus' 'Georgia' 'Iraq' 'Israel' 'Jordan' 'Kuwait' 'Lebanon'
 'Oman' 'Qatar' 'Saudi Arabia' 'State of Palestine (the)'
 'Syrian Arab Republic (the)' 'Türkiye' 'United Arab Emirates (the)'
 'Yemen' 'European Union (27)' 'Belarus' 'Bulgaria' 'Czechia' 'Hungary'
 'Kosovo' 'Poland' 'Republic of Moldova (the)' 'Romania'
 'Russian Federation (the)' 'Slovakia' 'Ukraine'
 'Residual/unallocated ODA: Northern America and Europe' 'Denmark'
 'Estonia' 'Faroe Islands' 'Finland' 'Iceland' 'Ireland' 'Latvia'
 'Lithuania' 'Norway' 'Sweden'
 'United Kingdom of Great Britain and Northern Ireland (the)' 'Albania'
 'Andorra' 'Bosnia and Herzegovina' 'Croatia' 'Greece' 'Italy' 'Malta'
 'Montenegro' 'North Macedonia' 'Portugal' 'Serbia' 'Slovenia' 'Spain'
 'Austria' 'Belgium' 'France' 'Germany' 'Luxembourg'
 'Netherlands (Kingdom of the)' 'Switzerland' 'Multilateral'
 'Residual/unallocated ODA: Oceania excl. Aus. and N. Zealand' 'Australia'
 'New Zealand' 'Fiji' 'New Caledonia' 'Papua New Guinea' 'Solomon Islands'
 'Vanuatu' 'Guam' 'Kiribati' 'Marshall Islands (the)'
 'Micronesia (Federated States of)' 'Nauru' 'Palau' 'American Samoa'
 'Cook Islands (the)' 'French Polynesia' 'Niue' 'Samoa' 'Tokelau' 'Tonga'
 'Tuvalu' 'Unspecified countries']

ISO3 code
  unique count: 235
  unique values: ['DZA' 'EGY' 'LBY' 'MAR' 'SDN' 'TUN' 'AGO' 'BEN' 'BWA' 'BFA' 'BDI' 'CPV'
 'CMR' 'CAF' 'TCD' 'COM' 'COG' 'CIV' 'COD' 'DJI' 'GNQ' 'ERI' 'SWZ' 'ETH'
 'GAB' 'GMB' 'GHA' 'GIN' 'GNB' 'KEN' 'LSO' 'LBR' 'MDG' 'MWI' 'MLI' 'MRT'
 'MUS' 'MYT' 'MOZ' 'NAM' 'NER' 'NGA' 'XAF' 'REU' 'RWA' 'SHN' 'STP' 'SEN'
 'SYC' 'SLE' 'SOM' 'ZAF' 'SSD' 'TGO' 'UGA' 'TZA' 'ZMB' 'ZWE' 'AIA' 'ATG'
 'ARG' 'ABW' 'BHS' 'BRB' 'BLZ' 'BOL' 'BES' 'BRA' 'VGB' 'CYM' 'CHL' 'COL'
 'CRI' 'CUB' 'CUW' 'DMA' 'DOM' 'ECU' 'SLV' 'FLK' 'GUF' 'GRD' 'GLP' 'GTM'
 'GUY' 'HTI' 'HND' 'JAM' 'MTQ' 'MEX' 'MSR' 'NIC' 'PAN' 'PRY' 'PER' 'PRI'
 'XLA' 'BLM' 'KNA' 'LCA' 'MAF' 'VCT' 'SXM' 'SGS' 'SUR' 'TTO' 'TCA' 'VIR'
 'URY' 'VEN' 'CAN' 'GRL' 'SPM' 'USA' 'XCS' 'XME' 'KAZ' 'KGZ' 'TJK' 'TKM'
 'UZB' 'CHN' 'HKG' 'TWN' 'PRK' 'JPN' 'MNG' 'KOR' 'XAS' 'BRN' 'KHM' 'IDN'
 'LAO' 'MYS' 'MMR' 'PHL' 'SGP' 'THA' 'TLS' 'VNM' 'AFG' 'BGD' 'BTN' 'IND'
 'IRN' 'MDV' 'NPL' 'PAK' 'LKA' 'ARM' 'AZE' 'BHR' 'CYP' 'GEO' 'IRQ' 'ISR'
 'JOR' 'KWT' 'LBN' 'OMN' 'QAT' 'SAU' 'PSE' 'SYR' 'TUR' 'ARE' 'YEM' 'EUE'
 'BLR' 'BGR' 'CZE' 'HUN' 'XKX' 'POL' 'MDA' 'ROU' 'RUS' 'SVK' 'UKR' 'XAA'
 'DNK' 'EST' 'FRO' 'FIN' 'ISL' 'IRL' 'LVA' 'LTU' 'NOR' 'SWE' 'GBR' 'ALB'
 'AND' 'BIH' 'HRV' 'GRC' 'ITA' 'MLT' 'MNE' 'MKD' 'PRT' 'SRB' 'SVN' 'ESP'
 'AUT' 'BEL' 'FRA' 'DEU' 'LUX' 'NLD' 'CHE' 'XMX' 'XOC' 'AUS' 'NZL' 'FJI'
 'NCL' 'PNG' 'SLB' 'VUT' 'GUM' 'KIR' 'MHL' 'FSM' 'NRU' 'PLW' 'ASM' 'COK'
 'PYF' 'NIU' 'WSM' 'TKL' 'TON' 'TUV' 'XDX']

M49 code
  unique count: 235
  unique values: [   12   818   434   504   729   788    24   204    72   854   108   132
   120   140   148   174   178   384   180   262   226   232   748   231
   266   270   288   324   624   404   426   430   450   454   466   478
   480   175   508   516   562   566 99039   638   646   654   678   686
   690   694   706   710   728   768   800   834   894   716   660    28
    32   533    44    52    84    68   535    76    92   136   152   170
   188   192   531   212   214   218   222   238   254   308   312   320
   328   332   340   388   474   484   500   558   591   600   604   630
 99037   652   659   662   663   670   534   239   740   780   796   850
   858   862   124   304   666   840 99035 99040   398   417   762   795
   860   156   344   158   408   392   496   410 99036    96   116   360
   418   458   104   608   702   764   626   704     4    50    64   356
   364   462   524   586   144    51    31    48   196   268   368   376
   400   414   422   512   634   682   275   760   792   784   887 99906
   112   100   203   348   412   616   498   642   643   703   804 99050
   208   233   234   246   352   372   428   440   578   752   826     8
    20    70   191   300   380   470   499   807   620   688   705   724
    40    56   250   276   442   528   756 99909 99038    36   554   242
   540   598    90   548   316   296   584   583   520   585    16   184
   258   570   882   772   776   798 99049]

RE or Non-RE
  unique count: 2
  unique values: ['Total Renewable' 'Total Non-Renewable']

Group Technology
  unique count: 12
  unique values: ['Bioenergy' 'Geothermal energy' 'Hydropower (excl. Pumped Storage)'
 'Marine energy' 'Multiple renewables*' 'Solar energy' 'Wind energy'
 'Other renewable energy' 'Fossil fuels' 'Nuclear'
 'Other non-renewable energy' 'Pumped storage']

Technology
  unique count: 23
  unique values: ['Solid biofuels' 'Geothermal energy' 'Renewable hydropower'
 'Marine energy' 'Multiple renewables*' 'Solar energy'
 'Solar photovoltaic' 'Solar thermal energy' 'Onshore wind energy'
 'Biogas' 'Liquid biofuels' 'Renewable municipal waste'
 'Mixed Hydro Plants' 'Offshore wind energy' 'Other renewable energy'
 'Natural gas' 'Oil' 'Nuclear' 'Coal and peat' 'Fossil fuels n.e.s.'
 'Non-renewable municipal waste' 'Pumped storage'
 'Other non-renewable energy']

Sub-Technology
  unique count: 47
  unique values: ['Other primary solid biofuels n.e.s.' 'Geothermal energy'
 'Renewable hydropower' 'Marine energy' 'Multiple renewables*'
 'Solar energy' 'Off-grid Solar photovoltaic' 'On-grid Solar photovoltaic'
 'Concentrated solar power' 'Onshore wind energy' 'Sewage sludge gas'
 'Bagasse' 'Landfill gas' 'Solar thermal energy' 'Biogas'
 'Other biogases from anaerobic fermentation' 'Other liquid biofuels'
 'Wood waste' 'Other vegetal and agricultural waste'
 'Renewable municipal waste' 'Rice husks' 'Conventional biodiesel'
 'Animal waste' 'Straw' 'Wood fuel' 'Liquid biofuels'
 'Conventional biogasoline' 'Biomass pellets and briquettes'
 'Biogases from thermal processes' 'Biodiesel' 'Biogasoline'
 'Black liquor' 'Energy crops' 'Biogas n.e.s.' 'Mixed Hydro Plants'
 'Offshore wind energy' 'Renewable industrial waste'
 'Other renewable energy' 'Other solar thermal energy' 'Natural gas' 'Oil'
 'Nuclear' 'Coal and peat' 'Fossil fuels n.e.s.'
 'Non-renewable municipal waste' 'Pumped storage'
 'Other non-renewable energy']

Producer Type
  unique count: 5
  unique values: ['All types' 'On-grid electricity' 'Off-grid electricity'
 'Combined Heat and Power (CHP)' 'Heat (Commercial)']

Year
  unique count: 25
  unique values: [2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013
 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024]

In [12]:
cat_uniques = {col: country_cat_df[col].unique() for col in country_cat_df.columns}
cat_unique_counts = country_cat_df.nunique(dropna=False)

In [13]:
country_cat_df.isnull().sum()

Region              0
Sub-region          0
Country             0
ISO3 code           0
M49 code            0
RE or Non-RE        0
Group Technology    0
Technology          0
Sub-Technology      0
Producer Type       0
Year                0
dtype: int64

In [14]:
country_num_df.isnull().sum()

Electricity Generation (GWh)                     54659
Electricity Installed Capacity (MW)              53356
Heat Generation (TJ)                             80575
Public Flows (2022 USD M)                        83314
SDG 7a1 Intl. Public Flows (2022 USD M)          86656
SDG 7b1 RE capacity per capita (W/inhabitant)    59631
dtype: int64

In [24]:
country_df["Technology"].value_counts()

Technology
Solid biofuels                   12684
Renewable hydropower             10815
Onshore wind energy               8558
Oil                               8220
Solar photovoltaic                7329
Geothermal energy                 6343
Marine energy                     5641
Solar energy                      5421
Biogas                            5126
Natural gas                       4716
Coal and peat                     3464
Fossil fuels n.e.s.               2369
Other non-renewable energy        2341
Multiple renewables*              2187
Renewable municipal waste         1680
Nuclear                           1639
Pumped storage                    1009
Liquid biofuels                    732
Solar thermal energy               469
Mixed Hydro Plants                 458
Offshore wind energy               340
Other renewable energy             168
Non-renewable municipal waste       34
Name: count, dtype: int64

In [25]:
country_df.groupby("Technology")["Electricity Generation (GWh)"].count()

Technology
Biogas                           3175
Coal and peat                    1919
Fossil fuels n.e.s.               315
Geothermal energy                 600
Liquid biofuels                   410
Marine energy                     243
Mixed Hydro Plants                  2
Multiple renewables*                0
Natural gas                      2632
Non-renewable municipal waste       0
Nuclear                           750
Offshore wind energy              267
Oil                              5984
Onshore wind energy              2933
Other non-renewable energy       1128
Other renewable energy              0
Pumped storage                    908
Renewable hydropower             5025
Renewable municipal waste         824
Solar energy                        0
Solar photovoltaic               5061
Solar thermal energy              212
Solid biofuels                   4696
Name: Electricity Generation (GWh), dtype: int64

The technology categories with 0 have no recorded electricity generation values in the dataset, likely due to aggregation, classification, or reporting limitations. The dataset mixes actual technologies (usable for analysis) and aggregate categories (should be filtered out). 
1.“Solar energy” is just a parent category, not a real measured one.
2.Multiple renewables* is probably combined/mixed sources and is not individually tracked. It is usually excluded in detailed analysis.
3.Other renewable energy is a vague category.It is often rarely reported and inconsistently used.
4.Non-renewable municipal waste can generate electricity, but may not be reported in the dataset.

In [26]:
invalid_tech = [
    "Solar energy",
    "Multiple renewables*",
    "Other renewable energy"
]

noinvalidtech_country_df = country_df[~country_df["Technology"].isin(invalid_tech)]

In [28]:
noinvalidtech_country_df.isna().sum()

Region                                               0
Sub-region                                           0
Country                                              0
ISO3 code                                            0
M49 code                                             0
RE or Non-RE                                         0
Group Technology                                     0
Technology                                           0
Sub-Technology                                       0
Producer Type                                        0
Year                                                 0
Electricity Generation (GWh)                     46883
Electricity Installed Capacity (MW)              45580
Heat Generation (TJ)                             72967
Public Flows (2022 USD M)                        77725
SDG 7a1 Intl. Public Flows (2022 USD M)          82019
SDG 7b1 RE capacity per capita (W/inhabitant)    57207
dtype: int64

In [32]:
noinvalidtech_country_df.shape

(83967, 17)

For Electricity Generation Analysis
The dataset still has missing values because; 1. Some countries didn’t report data, 2.Some technologies exist but had no production that year, 3. Some metrics don’t apply in certain cases

In [29]:
generation_df = noinvalidtech_country_df.dropna(subset=["Electricity Generation (GWh)"])

In [30]:
generation_df.isna().sum()

Region                                               0
Sub-region                                           0
Country                                              0
ISO3 code                                            0
M49 code                                             0
RE or Non-RE                                         0
Group Technology                                     0
Technology                                           0
Sub-Technology                                       0
Producer Type                                        0
Year                                                 0
Electricity Generation (GWh)                         0
Electricity Installed Capacity (MW)               3787
Heat Generation (TJ)                             37084
Public Flows (2022 USD M)                        37084
SDG 7a1 Intl. Public Flows (2022 USD M)          37084
SDG 7b1 RE capacity per capita (W/inhabitant)    37084
dtype: int64

In [31]:
generation_df.shape

(37084, 17)

Do not handle outliers because in energy data:
Countries like China, USA, Brazil produce HUGE amounts of electricity
Small countries produce very little
Those are not errors — they are real-world differences
So whhat looks like an “outlier” is often actually the most important insight

In [33]:
generation_df.describe()

,M49 code,Year,Electricity Generation (GWh),Electricity Installed Capacity (MW),Heat Generation (TJ),Public Flows (2022 USD M),SDG 7a1 Intl. Public Flows (2022 USD M),SDG 7b1 RE capacity per capita (W/inhabitant)
count,37084.000000,37084.000000,3.708400e+04,3.329700e+04,0.0,0.0,0.0,0.0
mean,420.032359,2012.851364,1.448429e+04,3.562165e+03,NaN,NaN,NaN,NaN
std,251.994260,6.763240,1.169155e+05,2.799575e+04,NaN,NaN,NaN,NaN
min,4.000000,2000.000000,-5.874050e+02,1.000000e-03,NaN,NaN,NaN,NaN
25%,203.000000,2007.000000,1.160750e+01,5.100000e+00,NaN,NaN,NaN,NaN
50%,404.000000,2014.000000,2.042565e+02,6.055000e+01,NaN,NaN,NaN,NaN
75%,630.000000,2019.000000,2.413088e+03,6.463000e+02,NaN,NaN,NaN,NaN
max,894.000000,2023.000000,5.579300e+06,1.200427e+06,NaN,NaN,NaN,NaN

The minimum value for Electricity Generation (the negative) is not realistic in this context. So all the negatives have to be removed. It could be it could be a data entry error or accounting adjustments (rare, but not useful for your analysis). The very high values are important in this context so should be maintained. The columns that show 0 count still exist but are entirely NaN in this filtered dataset. And so for this analysis we shall keep only the relevant columns.

In [34]:
generation_df = generation_df[generation_df["Electricity Generation (GWh)"] >= 0]

In [35]:
generation_df.describe()

,M49 code,Year,Electricity Generation (GWh),Electricity Installed Capacity (MW),Heat Generation (TJ),Public Flows (2022 USD M),SDG 7a1 Intl. Public Flows (2022 USD M),SDG 7b1 RE capacity per capita (W/inhabitant)
count,37079.000000,37079.000000,3.707900e+04,3.329200e+04,0.0,0.0,0.0,0.0
mean,420.019364,2012.851210,1.448628e+04,3.562561e+03,NaN,NaN,NaN,NaN
std,252.007396,6.763639,1.169233e+05,2.799783e+04,NaN,NaN,NaN,NaN
min,4.000000,2000.000000,1.000000e-03,1.000000e-03,NaN,NaN,NaN,NaN
25%,203.000000,2007.000000,1.161600e+01,5.100000e+00,NaN,NaN,NaN,NaN
50%,404.000000,2014.000000,2.044000e+02,6.055000e+01,NaN,NaN,NaN,NaN
75%,630.000000,2019.000000,2.414500e+03,6.456075e+02,NaN,NaN,NaN,NaN
max,894.000000,2023.000000,5.579300e+06,1.200427e+06,NaN,NaN,NaN,NaN

In [36]:
generation_df = generation_df[[
    "Country",
    "Region",
    "Technology",
    "Year",
    "Electricity Generation (GWh)"
]]

In [37]:
#Generation Over Time
gen_year = generation_df.groupby("Year")["Electricity Generation (GWh)"].sum().reset_index()

In [38]:
print(gen_year)

    Year  Electricity Generation (GWh)
0   2000                  1.555576e+07
1   2001                  1.566594e+07
2   2002                  1.627385e+07
3   2003                  1.685923e+07
4   2004                  1.762287e+07
5   2005                  1.838378e+07
6   2006                  1.909394e+07
7   2007                  1.991230e+07
8   2008                  2.032895e+07
9   2009                  2.023321e+07
10  2010                  2.158172e+07
11  2011                  2.230897e+07
12  2012                  2.285925e+07
13  2013                  2.350412e+07
14  2014                  2.385218e+07
15  2015                  2.426512e+07
16  2016                  2.491035e+07
17  2017                  2.572326e+07
18  2018                  2.667258e+07
19  2019                  2.708032e+07
20  2020                  2.702452e+07
21  2021                  2.840538e+07
22  2022                  2.915200e+07
23  2023                  2.986718e+07

In [39]:
#Generation by Technology
gen_tech = generation_df.groupby("Technology")["Electricity Generation (GWh)"].sum().reset_index()

In [40]:
print(gen_tech)

                    Technology  Electricity Generation (GWh)
0                       Biogas                  1.396291e+06
1                Coal and peat                  2.028056e+08
2          Fossil fuels n.e.s.                  6.687489e+06
3            Geothermal energy                  1.757157e+06
4              Liquid biofuels                  9.871120e+04
5                Marine energy                  1.752978e+04
6           Mixed Hydro Plants                  8.367938e+03
7                  Natural gas                  1.155741e+08
8                      Nuclear                  6.396384e+07
9         Offshore wind energy                  9.714812e+05
10                         Oil                  2.279245e+07
11         Onshore wind energy                  1.625617e+07
12  Other non-renewable energy                  2.554916e+06
13              Pumped storage                  2.463617e+06
14        Renewable hydropower                  8.482114e+07
15   Renewable municipal waste                  1.074051e+06
16          Solar photovoltaic                  7.513664e+06
17        Solar thermal energy                  1.442464e+05
18              Solid biofuels                  6.235985e+06

In [41]:
#Generation by Region
gen_region = generation_df.groupby("Region")["Electricity Generation (GWh)"].sum().reset_index()

In [42]:
print(gen_region)

     Region  Electricity Generation (GWh)
0    Africa                  1.624793e+07
1  Americas                  1.531431e+08
2      Asia                  2.455905e+08
3    Europe                  1.149496e+08
4   Oceania                  7.205642e+06

In [43]:
#Top Countries
top_countries = (
    generation_df.groupby("Country")["Electricity Generation (GWh)"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)

In [44]:
print(top_countries)

                          Country  Electricity Generation (GWh)
0                           China                  1.172849e+08
1  United States of America (the)                  1.027471e+08
2                           India                  2.616904e+07
3                           Japan                  2.585826e+07
4        Russian Federation (the)                  2.515573e+07
5                          Canada                  1.516845e+07
6                         Germany                  1.471926e+07
7                          France                  1.343561e+07
8                          Brazil                  1.242208e+07
9         Republic of Korea (the)                  1.163756e+07

Save as CSVs to move to powerBI

In [45]:
gen_year.to_csv("gen_year.csv", index=False)
gen_tech.to_csv("gen_tech.csv", index=False)
gen_region.to_csv("gen_region.csv", index=False)
top_countries.to_csv("top_countries.csv", index=False)